[package]
name = "tessera-scene"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
tessera-types.workspace = true
serde.workspace = true
[features]
default = ["serde"]
serde = []
[dev-dependencies]
serde_json.workspace = true
[lints]
workspace = true
